/*
 * xbar.h
 *
 *  Created on: 19 may. 2024
 *      Author: Dr. Carlos Romero
 */

#ifndef KERNEL_INCLUDES_PRIVATED_XBAR_H_
#define KERNEL_INCLUDES_PRIVATED_XBAR_H_

#include    <kernel_types.h>
#include    <f28004x_input_xbar.h>
#include    <f28004x_output_xbar.h>
#include    <f28004x_epwm_xbar.h>
#include    <f28004x_clbxbar.h>
#include    <f28004x_xbar.h>

#define NOTUSED_SET0            0xFFFF
#define NOTUSED_SET1            0xFFFE



enum MUX0_PWM_XBAR {CMPSS1_CTRIPH_PWM, CMPSS1_CTRIPH_OR_CTRIPL_PWM, ADCAEVT1_PWM, ECAP1OUT_PWM};
enum MUX1_PWM_XBAR {CMPSS1_CTRIPL_PWM, INPUTXBAR1_PWM, CLB1_OUT4_PWM, ADCCEVT1_PWM};
enum MUX2_PWM_XBAR {CMPSS2_CTRIPH_PWM, CMPSS2_CTRIPH_OR_CTRIPL_PWM, ADCAEVT2_PWM, ECAP2OUT_PWM};
enum MUX3_PWM_XBAR {CMPSS2_CTRIPL_PWM, INPUTXBAR2_PWM, CLB1_OUT5_PWM, ADCCEVT2_PWM};
enum MUX4_PWM_XBAR {CMPSS3_CTRIPH_PWM, CMPSS3_CTRIPH_OR_CTRIPL_PWM, ADCAEVT3_PWM, ECAP3OUT_PWM};
enum MUX5_PWM_XBAR {CMPSS3_CTRIPL_PWM, INPUTXBAR3_PWM, CLB2_OUT4_PWM, ADCCEVT3_PWM};
enum MUX6_PWM_XBAR {CMPSS4_CTRIPH_PWM, CMPSS4_CTRIPH_OR_CTRIPL_PWM, ADCAEVT4_PWM, ECAP4OUT_PWM};
enum MUX7_PWM_XBAR {CMPSS4_CTRIPL_PWM, INPUTXBAR4_PWM, CLB2_OUT5_PWM, ADCCEVT4_PWM};
enum MUX8_PWM_XBAR {CMPSS5_CTRIPH_PWM, CMPSS5_CTRIPH_OR_CTRIPL_PWM, ADCBEVT1_PWM, ECAP5OU_PWM};
enum MUX9_PWM_XBAR {CMPSS5_CTRIPL_PWM, INPUTXBAR5, CLB3_OUT4_PWM};
enum MUX10_PWM_XBAR{CMPSS6_CTRIPH_PWM, CMPSS6_CTRIPH_OR_CTRIPL_PWM, ADCBEVT2_PWM, ECAP6OUT_PWM};
enum MUX11_PWM_XBAR{CMPSS6_CTRIPL_PWM, INPUTXBAR6_PWM, CLB3_OUT5_PWM};
enum MUX12_PWM_XBAR{CMPSS7_CTRIPH_PWM, CMPSS7_CTRIPH_OR_CTRIPL_PWM, ADCBEVT3_PWM, ECAP7OUT_PWM};
enum MUX13_PWM_XBAR{CMPSS7_CTRIPL_PWM, ADCSOCAO_PWM, CLB4_OUT4_PWM};
enum MUX14_PWM_XBAR{ADCBEVT4_PWM=2,EXTSYNCOUT_PWM};
enum MUX15_PWM_XBAR{ADCSOCBO_PWM=1, CLB4_OUT5_PWM};
enum MUX16_PWM_XBAR{SD1FLT1_COMPH_PWM, SD1FLT1_COMPH_OR_COMPL_PWM};
enum MUX17_PWM_XBAR{SD1FLT1_COMPL_PWM, INPUTXBAR7_PWM, CLAHALT_PWM=3};
enum MUX18_PWM_XBAR{SD1FLT2_COMPH_PWM, SD1FLT2_COMPH_OR_COMPL_PWM};
enum MUX19_PWM_XBAR{SD1FLT2_COMPL_PWM, INPUTXBAR8_PWM};
enum MUX20_PWM_XBAR{SD1FLT3_COMPH_PWM, SD1FLT3_COMPH_OR_COMPL_PWM};
enum MUX21_PWM_XBAR{SD1FLT3_COMPL_PWM, INPUTXBAR9_PWM};
enum MUX22_PWM_XBAR{SD1FLT4_COMPH_PWM, SD1FLT4_COMPH_OR_COMPL_PWM};
enum MUX23_PWM_XBAR{SD1FLT4_COMPL_PWM, INPUTXBAR10_PWM};
enum MUX25_PWM_XBAR{INPUTXBAR11_PWM=1};
enum MUX27_PWM_XBAR{INPUTXBAR12_PWM=1};
enum MUX29_PWM_XBAR{INPUTXBAR13_PWM=1};
enum MUX31_PWM_XBAR{INPUTXBAR14_PWM=1};

enum MUX0_OUTPUT_XBAR{CMPSS1_CTRIPOUTH_OUTPUT, CMPSS1_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCAEVT1_0_OUTPUT, ECAP1OUT_OUTPUT};
enum MUX1_OUTPUT_XBAR{CMPSS1_CTRIPOUTL_OUTPUT, INPUTXBAR1_OUTPUT, CLB1_OUT4_1_OUTPUT, ADCCEVT1_1_OUTPUT};
enum MUX2_OUTPUT_XBAR{CMPSS2_CTRIPOUTH_OUTPUT, CMPSS2_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCAEVT2_2_OUTPUT, ECAP2OUT_OUTPUT};
enum MUX3_OUTPUT_XBAR{CMPSS2_CTRIPOUTL_OUTPUT, INPUTXBAR2_OUTPUT, CLB1_OUT5_1_OUTPUT, ADCCEVT2_3_OUTPUT};
enum MUX4_OUTPUT_XBAR{CMPSS3_CTRIPOUTH_OUTPUT, CMPSS3_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCAEVT3_4_OUTPUT, ECAP3OUT_OUTPUT};
enum MUX5_OUTPUT_XBAR{CMPSS3_CTRIPOUTL_OUTPUT, INPUTXBAR3_OUTPUT, CLB2_OUT4_1_OUTPUT, ADCCEVT3_5_OUTPUT};
enum MUX6_OUTPUT_XBAR{CMPSS4_CTRIPOUTH_OUTPUT, CMPSS4_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCAEVT4_6_OUTPUT, ECAP4OUT_OUTPUT};
enum MUX7_OUTPUT_XBAR{CMPSS4_CTRIPOUTL_OUTPUT, INPUTXBAR4_OUTPUT, CLB2_OUT5_1_OUTPUT, ADCCEVT4_7_OUTPUT};
enum MUX8_OUTPUT_XBAR{CMPSS5_CTRIPOUTH_OUTPUT, CMPSS5_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCBEVT1_8_OUTPUT, ECAP5OUT_OUTPUT};
enum MUX9_OUTPUT_XBAR{CMPSS5_CTRIPOUTL_OUTPUT, INPUTXBAR5_OUTPUT, CLB3_OUT4_1_OUTPUT};
enum MUX10_OUTPUT_XBAR{CMPSS6_CTRIPOUTH_OUTPUT, CMPSS6_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCBEVT2_10_OUTPUT, ECAP6OUT_OUTPUT};
enum MUX11_OUTPUT_XBAR{CMPSS6_CTRIPOUTL_OUTPUT, INPUTXBAR6_OUTPUT, CLB3_OUT5_1_OUTPUT};
enum MUX12_OUTPUT_XBAR{CMPSS7_CTRIPOUTH_OUTPUT, CMPSS7_CTRIPOUTH_OR_CTRIPOUTL_OUTPUT, ADCBEVT3_12_OUTPUT, ECAP7OUT_OUTPUT};
enum MUX13_OUTPUT_XBAR{CMPSS7_CTRIPOUTL_OUTPUT, ADCSOCAO_OUTPUT, CLB4_OUT4_1_OUTPUT};
enum MUX14_OUTPUT_XBAR{ADCBEVT4_OUTPUT=2, EXTSYNCOUT_OUTPUT};
enum MUX15_OUTPUT_XBAR{ADCSOCBO_OUTPUT=1, CLB4_OUT5_1_OUTPUT};
enum MUX16_OUTPUT_XBAR{SD1FLT1_COMPH_OUTPUT, SD1FLT1_COMPH_OR_COMPL_OUTPUT};
enum MUX17_OUTPUT_XBAR{SD1FLT1_COMPL_OUTPUT,CLAHALT_OUTPUT=3};
enum MUX18_OUTPUT_XBAR{SD1FLT2_COMPH_OUTPUT, SD1FLT2_COMPH_OR_COMPL_OUTPUT};
enum MUX19_OUTPUT_XBAR{SD1FLT2_COMPL_OUTPUT};
enum MUX20_OUTPUT_XBAR{SD1FLT3_COMPH_OUTPUT, SD1FLT3_COMPH_OR_COMPL_OUTPUT};
enum MUX21_OUTPUT_XBAR{SD1FLT3_COMPL_OUTPUT};
enum MUX22_OUTPUT_XBAR{SD1FLT4_COMPH_OUTPUT, SD1FLT4_COMPH_OR_COMPL_OUTPUT};
enum MUX23_OUTPUT_XBAR{SD1FLT4_COMPL_OUTPUT};

enum MUX0_CLB_XBAR{CMPSS1_CTRIPOUTH_CLB, CMPSS1_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCAEVT1_CLB, ECAP1OUT_CLB};
enum MUX1_CLB_XBAR{CMPSS1_CTRIPOUTL_CLB, INPUTXBAR1_CLB, CLB1_OUT4_CLB, ADCCEVT1_CLB};
enum MUX2_CLB_XBAR{CMPSS2_CTRIPOUTH_CLB, CMPSS2_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCAEVT2_CLB, ECAP2OUT_CLB};
enum MUX3_CLB_XBAR{CMPSS2_CTRIPOUTL_CLB, INPUTXBAR2_CLB, CLB1_OUT5_CLB, ADCCEVT2_CLB};
enum MUX4_CLB_XBAR{CMPSS3_CTRIPOUTH_CLB, CMPSS3_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCAEVT3_CLB, ECAP3OUT_CLB};
enum MUX5_CLB_XBAR{CMPSS3_CTRIPOUTL_CLB, INPUTXBAR3_CLB_CLB, CLB2_OUT4_CLB, ADCCEVT3_CLB};
enum MUX6_CLB_XBAR{CMPSS4_CTRIPOUTH_CLB, CMPSS4_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCAEVT4_CLB, ECAP4OUT_CLB};
enum MUX7_CLB_XBAR{CMPSS4_CTRIPOUTL_CLB, INPUTXBAR4_CLB, CLB2_OUT5_CLB, ADCCEVT4_CLB};
enum MUX8_CLB_XBAR{CMPSS5_CTRIPOUTH_CLB, CMPSS5_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCBEVT1_CLB, ECAP5OUT_CLB};
enum MUX9_CLB_XBAR{CMPSS5_CTRIPOUTL_CLB, INPUTXBAR5_CLB, CLB3_OUT4_CLB};
enum MUX10_CLB_XBAR{CMPSS6_CTRIPOUTH_CLB, CMPSS6_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCBEVT2_CLB, ECAP6OUT_CLB};
enum MUX11_CLB_XBAR{CMPSS6_CTRIPOUTL_CLB, INPUTXBAR6_CLB, CLB3_OUT5_CLB};
enum MUX12_CLB_XBAR{CMPSS7_CTRIPOUTH_CLB, CMPSS7_CTRIPOUTH_OR_CTRIPOUTL_CLB, ADCBEVT3_CLB, ECAP7OUT_CLB};
enum MUX13_CLB_XBAR{CMPSS7_CTRIPOUTL_CLB, ADCSOCAO_CLB, CLB4_OUT4_CLB};
enum MUX14_CLB_XBAR{ADCBEVT4_CLB=2, EXTSYNCOUT_CLB};
enum MUX15_CLB_XBAR{ADCSOCBO_CLB=1, CLB4_OUT5_CLB};
enum MUX16_CLB_XBAR{SD1FLT1_COMPH_CLB, SD1FLT1_COMPH_OR_COMPL_CLB, SD1FLT1_COMPZ_CLB, SD1FLT1_DRINT_CLB};
enum MUX17_CLB_XBAR{SD1FLT1_COMPL_CLB, INPUTXBAR7_CLB, CLAHALT_CLB=3};
enum MUX18_CLB_XBAR{SD1FLT2_COMPH_CLB, SD1FLT2_COMPH_OR_COMPL_CLB, SD1FLT2_COMPZ_CLB, SD1FLT2_DRINT_CLB};
enum MUX19_CLB_XBAR{SD1FLT2_COMPL_CLB, INPUTXBAR8_CLB};
enum MUX20_CLB_XBAR{SD1FLT3_COMPH_CLB, SD1FLT3_COMPH_OR_COMPL_CLB, SD1FLT3_COMPZ_CLB, SD1FLT3_DRINT_CLB};
enum MUX21_CLB_XBAR{SD1FLT3_COMPL_CLB, INPUTXBAR9_CLB};
enum MUX22_CLB_XBAR{SD1FLT4_COMPH_CLB, SD1FLT4_COMPH_OR_COMPL_CLB, SD1FLT4_COMPZ_CLB, SD1FLT4_DRINT_CLB};
enum MUX23_CLB_XBAR{SD1FLT4_COMPL_CLB, INPUTXBAR10_CLB};
enum MUX25_CLB_XBAR{INPUTXBAR11_CLB=1};
enum MUX27_CLB_XBAR{INPUTXBAR12_CLB=1};
enum MUX29_CLB_XBAR{INPUTXBAR13_CLB=1};
enum MUX31_CLB_XBAR{INPUTXBAR14_CLB=1};



typedef struct
{
    void (* Set_Inputxbar) (Uint16,Uint16);

} clase_inputxbar;

typedef struct
{
    void ( * Set_OutputMux0Xbar)(Uint16,enum MUX0_OUTPUT_XBAR);
    void ( * Set_OutputMux1Xbar)(Uint16,enum MUX1_OUTPUT_XBAR);
    void ( * Set_OutputMux2Xbar)(Uint16,enum MUX2_OUTPUT_XBAR);
    void ( * Set_OutputMux3Xbar)(Uint16,enum MUX3_OUTPUT_XBAR);
    void ( * Set_OutputMux4Xbar)(Uint16,enum MUX4_OUTPUT_XBAR);
    void ( * Set_OutputMux5Xbar)(Uint16,enum MUX5_OUTPUT_XBAR);
    void ( * Set_OutputMux6Xbar)(Uint16,enum MUX6_OUTPUT_XBAR);
    void ( * Set_OutputMux7Xbar)(Uint16,enum MUX7_OUTPUT_XBAR);
    void ( * Set_OutputMux8Xbar)(Uint16,enum MUX8_OUTPUT_XBAR);
    void ( * Set_OutputMux9Xbar)(Uint16,enum MUX9_OUTPUT_XBAR);
    void ( * Set_OutputMux10Xbar)(Uint16,enum MUX10_OUTPUT_XBAR);
    void ( * Set_OutputMux11Xbar)(Uint16,enum MUX11_OUTPUT_XBAR);
    void ( * Set_OutputMux12Xbar)(Uint16,enum MUX12_OUTPUT_XBAR);
    void ( * Set_OutputMux13Xbar)(Uint16,enum MUX13_OUTPUT_XBAR);
    void ( * Set_OutputMux14Xbar)(Uint16,enum MUX14_OUTPUT_XBAR);
    void ( * Set_OutputMux15Xbar)(Uint16,enum MUX15_OUTPUT_XBAR);
    void ( * Set_OutputMux16Xbar)(Uint16,enum MUX16_OUTPUT_XBAR);
    void ( * Set_OutputMux17Xbar)(Uint16,enum MUX17_OUTPUT_XBAR);
    void ( * Set_OutputMux18Xbar)(Uint16,enum MUX18_OUTPUT_XBAR);
    void ( * Set_OutputMux19Xbar)(Uint16,enum MUX19_OUTPUT_XBAR);
    void ( * Set_OutputMux20Xbar)(Uint16,enum MUX20_OUTPUT_XBAR);
    void ( * Set_OutputMux21Xbar)(Uint16,enum MUX21_OUTPUT_XBAR);
    void ( * Set_OutputMux22Xbar)(Uint16,enum MUX22_OUTPUT_XBAR);
    void ( * Set_OutputMux23Xbar)(Uint16,enum MUX23_OUTPUT_XBAR);
    void ( * Set_OutputMuxEnabler)(Uint16,Uint32);
    void ( * Set_OutputOutInvert)(Uint16,bool);

} clase_outputxbar;

typedef struct
{
    void (* Set_Pwmmux0xbar)(Uint16,enum MUX0_PWM_XBAR);
    void (* Set_Pwmmux1xbar)(Uint16,enum MUX1_PWM_XBAR);
    void (* Set_Pwmmux2xbar)(Uint16,enum MUX2_PWM_XBAR);
    void (* Set_Pwmmux3xbar)(Uint16,enum MUX3_PWM_XBAR);
    void (* Set_Pwmmux4xbar)(Uint16,enum MUX4_PWM_XBAR);
    void (* Set_Pwmmux5xbar)(Uint16,enum MUX5_PWM_XBAR);
    void (* Set_Pwmmux6xbar)(Uint16,enum MUX6_PWM_XBAR);
    void (* Set_Pwmmux7xbar)(Uint16,enum MUX7_PWM_XBAR);
    void (* Set_Pwmmux8xbar)(Uint16,enum MUX8_PWM_XBAR);
    void (* Set_Pwmmux9xbar)(Uint16,enum MUX9_PWM_XBAR);
    void (* Set_Pwmmux10xbar)(Uint16,enum MUX10_PWM_XBAR);
    void (* Set_Pwmmux11xbar)(Uint16,enum MUX11_PWM_XBAR);
    void (* Set_Pwmmux12xbar)(Uint16,enum MUX12_PWM_XBAR);
    void (* Set_Pwmmux13xbar)(Uint16,enum MUX13_PWM_XBAR);
    void (* Set_Pwmmux14xbar)(Uint16,enum MUX14_PWM_XBAR);
    void (* Set_Pwmmux15xbar)(Uint16,enum MUX15_PWM_XBAR);
    void (* Set_Pwmmux16xbar)(Uint16,enum MUX16_PWM_XBAR);
    void (* Set_Pwmmux17xbar)(Uint16,enum MUX17_PWM_XBAR);
    void (* Set_Pwmmux18xbar)(Uint16,enum MUX18_PWM_XBAR);
    void (* Set_Pwmmux19xbar)(Uint16,enum MUX19_PWM_XBAR);
    void (* Set_Pwmmux20xbar)(Uint16,enum MUX20_PWM_XBAR);
    void (* Set_Pwmmux21xbar)(Uint16,enum MUX21_PWM_XBAR);
    void (* Set_Pwmmux22xbar)(Uint16,enum MUX22_PWM_XBAR);
    void (* Set_Pwmmux23xbar)(Uint16,enum MUX23_PWM_XBAR);
    void (* Set_Pwmmux25xbar)(Uint16,enum MUX25_PWM_XBAR);
    void (* Set_Pwmmux27xbar)(Uint16,enum MUX27_PWM_XBAR);
    void (* Set_Pwmmux29xbar)(Uint16,enum MUX29_PWM_XBAR);
    void (* Set_Pwmmux31xbar)(Uint16,enum MUX31_PWM_XBAR);
    void (* Set_Pwmmuxenabler)(Uint16,Uint32);
    void (* Set_PwmOutputInvert)(Uint16,bool);
} clase_pwmxbar;

typedef struct
{
    void (* Set_CLBMux0Xbar)(Uint16,enum MUX0_CLB_XBAR);
    void (* Set_CLBMux1Xbar)(Uint16,enum MUX1_CLB_XBAR);
    void (* Set_CLBMux2Xbar)(Uint16,enum MUX2_CLB_XBAR);
    void (* Set_CLBMux3Xbar)(Uint16,enum MUX3_CLB_XBAR);
    void (* Set_CLBMux4Xbar)(Uint16,enum MUX4_CLB_XBAR);
    void (* Set_CLBMux5Xbar)(Uint16,enum MUX5_CLB_XBAR);
    void (* Set_CLBMux6Xbar)(Uint16,enum MUX6_CLB_XBAR);
    void (* Set_CLBMux7Xbar)(Uint16,enum MUX7_CLB_XBAR);
    void (* Set_CLBMux8Xbar)(Uint16,enum MUX8_CLB_XBAR);
    void (* Set_CLBMux9Xbar)(Uint16,enum MUX9_CLB_XBAR);
    void (* Set_CLBMux10Xbar)(Uint16,enum MUX10_CLB_XBAR);
    void (* Set_CLBMux11Xbar)(Uint16,enum MUX11_CLB_XBAR);
    void (* Set_CLBMux12Xbar)(Uint16,enum MUX12_CLB_XBAR);
    void (* Set_CLBMux13Xbar)(Uint16,enum MUX13_CLB_XBAR);
    void (* Set_CLBMux14Xbar)(Uint16,enum MUX14_CLB_XBAR);
    void (* Set_CLBMux15Xbar)(Uint16,enum MUX15_CLB_XBAR);
    void (* Set_CLBMux16Xbar)(Uint16,enum MUX16_CLB_XBAR);
    void (* Set_CLBMux17Xbar)(Uint16,enum MUX17_CLB_XBAR);
    void (* Set_CLBMux18Xbar)(Uint16,enum MUX18_CLB_XBAR);
    void (* Set_CLBMux19Xbar)(Uint16,enum MUX19_CLB_XBAR);
    void (* Set_CLBMux20Xbar)(Uint16,enum MUX20_CLB_XBAR);
    void (* Set_CLBMux21Xbar)(Uint16,enum MUX21_CLB_XBAR);
    void (* Set_CLBMux22Xbar)(Uint16,enum MUX22_CLB_XBAR);
    void (* Set_CLBMux23Xbar)(Uint16,enum MUX23_CLB_XBAR);
    void (* Set_CLBMuxEnabler)(Uint16,Uint32);
    void (* Set_CLBOutInvert)(Uint16,bool);

} clase_clbxbar;

typedef struct
{
    clase_inputxbar * input;
    clase_outputxbar * output;
    clase_pwmxbar * pwm;
    clase_clbxbar * clb;

} clase_xbar;

extern clase_xbar xbar;

#endif /* KERNEL_INCLUDES_PRIVATED_XBAR_H_ */
